name: speedpad_service
version: 0.0.1
description: Service Helper for Speedpad Chrome Extension
dependencies:
  browser: any
  chrome: "^0.8.0"
  web_components: "^0.12.0+3"
  dart_to_js_script_rewriter: "^0.1.0+4"
  event_bus: "^0.4.1"
  image: "^1.1.25"
  shared_classes:
    path: "../shared-classes"
  serialization: "^0.10.4+2"
  dart_switch: "^0.2.0"
  logging: "^0.11.2"
  logging_handlers: "^0.8.0"

dev_dependencies:
  test: "^0.12.6"

transformers:
- $dart2js:
    minify: false
    csp: true
    sourceMaps: true
- chrome
- dart_to_js_script_rewriter
